### ISSUE TITLE
RPI2040 motor driver

### ISSUE THREAD

**Issue by samuk** [kubabuda/ecat_servo#6]
AFAIK this is one of the only open hardware BLDC drivers: https://github.com/Twisted-Fields/rp2040-motor-controller#readme

I mentioned your project here: https://community.twistedfields.com/t/software-stack-why-not-ros/67/19?u=sam_uk

I don't know if Taylor would want to add it directly to the main board, but they may do. But the board could always be forked?

**Comment by kubabuda** [comment]
There are plenty of OSS BLDC motor drivers, I am targetting STMBL. Unless you mean specifically BLDC drivers with RP2040 for some reason, I havent seen many of those, maybe because reading specs this MCU is not best suited for motion control

One hurdle I see looking at integrating with this project is that this is 2 axis device. I do not need multiaxis nodes and I had not implemented this.

**Comment by samuk** [comment]
Great I only know about that pi one since odrive closed their hardware. I see the STMBL [Eagle now](https://github.com/rene-dev/stmbl/tree/eaa906aa9c898b4f468240f0bb984a64953dc099/hw/eagle)

Do you know of any others? Shame you can only do a single channel..

**Comment by kubabuda** [comment]
STMBL is designed in KiCad and all files are in /hw subdir
For more OSS designs there is legacy VESC versions, and plenty of SimpleFOC boards on their forum.

Multiple CiA402 axis can be done with SOES and my lib, I just have no usecase for this for now so I had not implemented it.

What are you trying to build and what ethercat features make it good fit for application? Linked project is small BLDC driver, adding ecat adapter will probably double your BOM

**Comment by samuk** [comment]
I'm interested in the context of this medium-scale Ag rover: https://github.com/Twisted-Fields It would connect the drive/steering motor drivers to the central CPU.
